services:
  app:
    build: .
    ports:
      - "24212:3000"
    volumes:
      - .:/app
      - /app/node_modules
      - /app/.next
    env_file:
      - .env
    environment:
      - NODE_ENV=production
      - MONGODB_URI=${MONGODB_URI}
      - USERNAME=${USERNAME}
      - PASSWORD=${PASSWORD}
      - TORRENT_SERVICE_URL=http://torrent-service:3001
    depends_on:
      - mongodb
      - torrent-service

  mongodb:
    image: mongo:latest
    ports:
      - "24213:27017"
    volumes:
      - ./data/mongodb:/data/db
    environment:
      - MONGO_INITDB_DATABASE=rssfeed

  torrent-service:
    build:
      context: .
      dockerfile: services/torrent-service/Dockerfile
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=production
    volumes:
      - ./src/types:/app/src/types
      - ./services/torrent-service:/app/services/torrent-service
      - /app/node_modules

volumes:
  mongodb_data:
