services:
  app:
    build: .
    ports:
      - "24212:3000"
    volumes:
      - .:/app
      - /app/node_modules
      - /app/.next
    env_file:
      - .env
    environment:
      - MONGODB_URI=${MONGODB_URI}
      - NODE_ENV=production
      - USERNAME=${USERNAME}
      - PASSWORD=${PASSWORD}

    depends_on:
      - mongodb

  mongodb:
    image: mongo:latest
    ports:
      - "24213:27017"
    volumes:
      - ./data/mongodb:/data/db
    environment:
      - MONGO_INITDB_DATABASE=rssfeed

volumes:
  mongodb_data:
